apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
  namespace: bank-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank-container
        image: acrbankdemo.azurecr.io/bank-app:latest
        ports:
        - containerPort: 8080
